cluster.name: escluster_dev
network.host: 0.0.0.0
cluster.initial_master_nodes: esmaster-0
logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
logger.org.elasticsearch.discovery: TRACE
