cluster.name: escluster_dev
network.host: 0.0.0.0
cluster.initial_master_nodes: ["esmaster-0", "esmaster-1", "esmaster-2"]
logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
logger.org.elasticsearch.discovery: TRACE
